name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'

      - name: Print Flutter version
        run: flutter --version

      - name: Get Flutter dependencies
        working-directory: FlutterApp
        run: flutter pub get

      - name: Build APK for arm64 and armeabi-v7a
        working-directory: FlutterApp
        run: flutter build apk --release --target-platform android-arm,android-arm64

      - name: Build AAB
        working-directory: FlutterApp
        run: flutter build appbundle --release

      - name: Upload libflutter.so for arm64
        uses: actions/upload-artifact@v4
        with:
          name: libflutter_so_arm64
          path: FlutterApp/build/app/intermediates/flutter/release/arm64-v8a/libflutter.so

      - name: Upload libflutter.so for armeabi-v7a
        uses: actions/upload-artifact@v4
        with:
          name: libflutter_so_armeabi_v7a
          path: FlutterApp/build/app/intermediates/flutter/release/armeabi-v7a/libflutter.so

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: FlutterApp/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: FlutterApp/build/app/outputs/bundle/release/app-release.aab
